### ISSUE TITLE
Portfolio - Dev Card

### ISSUE THREAD

**Issue by CodeByDex** [CodeByDex/OIODev#12]
Name - Dave Developer
Title - Passionate Web Developer Focused on Front End Dev
Bio - Word Vomit
Photo Link 
Availability to Work - Yes/No?
Personal Portfolio (Optional)
LinkedIn (Optional)
Github (Optional)
Services & Rate
Calendry API Key (MVP2)
Stripe API Key (MVP3)

**Comment by that-devguy** [comment]
Needs GraphQL data
Calendly API (MVP2)
Stripe API Key (MVP3)

**Comment by CodeByDex** [comment]
I feel like this should be broken apart, it's too many things

**Comment by that-devguy** [comment]
Agreed, I've pretty much closed this issue other than the mvp2 and 3 items.
