### ISSUE TITLE
Home Page Landing Component - first impressions matter 

### ISSUE THREAD

**Issue by CodeByDex** [CodeByDex/OIODev#30]

**Comment by CodeByDex** [comment]
I think you might have completed this?

**Comment by ChelseaLuevano** [comment]
I'd like to still review with @that-devguy as I have some ideas for improvement. @that-devguy would you want to pair on this? I want to learn from the front-end design guru!

**Comment by that-devguy** [comment]
Yeah, we can look at this tonight when we meet with the whole team or we can pair up during lecture hours tomorrow to work on it.
